# Autogenerated wrapper script for ECharts_jll for any
export echarts

JLLWrappers.@generate_wrapper_header("ECharts")
JLLWrappers.@declare_file_product(echarts)
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_file_product(
        echarts,
        "node_modules/echarts/dist/echarts.js",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
